import numpy as np ; 

PENN_TB_POS_TAGS = {
	"CC"   : (1 ,"Coordinating conjunction") ,
	"CD"   : (2 ,"Cardinal number") ,
	"DT"   : (3 ,"Determiner") ,
	"EX"	 : (4 ,"Existential there") ,
	"FW"	 : (5 ,"Foreign word") ,
	"IN"	 : (6 ,"Preposition or subordinating conjunction") ,
	"JJ"	 : (7 ,"Adjective") ,
	"JJR"	 : (8 ,"Adjective, comparative") ,
	"JJS"	 : (9 ,"Adjective, superlative") ,
	"LS"	 : (10 ,"List item marker") ,
	"MD"	 : (11 ,"Modal") ,
	"NN"	 : (12 ,"Noun, singular or mass") ,
	"NNS"	 : (13 ,"Noun, plural") ,
	"NNP"	 : (14 ,"Proper noun, singular") ,
	"NNPS" : (15 ,"Proper noun, plural") ,
	"PDT"	 : (16 ,"Predeterminer") ,
	"POS"	 : (17 ,"Possessive ending") ,
	"PRP"	 : (18 ,"Personal pronoun") ,
	"PRP$" : (19 ,"Possessive pronoun") ,
	"RB"	 : (20 ,"Adverb") ,
	"RBR"	 : (21 ,"Adverb, comparative") ,
	"RBS"	 : (22 ,"Adverb, superlative") ,
	"RP"	 : (23 ,"Particle") ,
	"SYM"	 : (24 ,"Symbol") ,
	"TO"	 : (25 ,"to") ,
	"UH"	 : (26 ,"Interjection") ,
	"VB"	 : (27 ,"Verb, base form") ,
	"VBD"	 : (28 ,"Verb, past tense") ,
	"VBG"	 : (29 ,"Verb, gerund or present participle") ,
	"VBN"	 : (30 ,"Verb, past participle") ,
	"VBP"	 : (31 ,"Verb, non-3rd person singular present") ,
	"VBZ"	 : (32 ,"Verb, 3rd person singular present") ,
	"WDT"	 : (33 ,"Wh-determiner") ,
	"WP"	 : (34 ,"Wh-pronoun") ,
	"WP$"	 : (35 ,"Possessive wh-pronoun") ,
	"WRB"	 : (36 ,"Wh-adverb"), 
     "AUXG": (37 ,"?"),
     "AUX" : (38 ,"UD POSTAG"), 
     "ADJ"  :(39 , "UD POSTAG"),
     "ADV"  :(40 , "UD POSTAG"), 
     "INTJ" :(41 , "UD POSTAG"),
     "NOUN" :(42 , "UD POSTAG"),
     "PROPN":(43 , "UD POSTAG"),
     "VERB" :(44 , "UD POSTAG"),
     "ADP"  :(45 , "UD POSTAG"),
     "CCONJ":(46 , "UD POSTAG"),
     "CONJ" :(47 , "OLD UD POSTAG"),
     "DET"  :(48 , "UD POSTAG"),
     "NUM"  :(49 , "UD POSTAG"),
     "PART" :(50 , "UD POSTAG"),
     "PRON" :(51 , "UD POSTAG"),
     "SCONJ":(52 , "UD POSTAG"),
     "PUNCT":(53 , "UD POSTAG"),
     "X"    :(54 , "UD POSTAG"),    
     "PRT"  :(55 , "SyntaxNet POSTAG"),
     "ADDED_OTHER" : (56 , "Added by farrokh for punctuations")  
      #"ADDED_EOS"   : (38 , "Added by farrokh for end-of-sentence if punctuation") this was never used ... 
 }
 
STANFORD_DEPTP_TAGS = {
        'L_abbrev'                      : (1 , '99033'),
        'R_abbrev'                      : (2 , '99033'),
        'L_acomp'                       : (3 , '8118'),
        'R_acomp'                       : (4 , '8118'),
        'L_advcl'                       : (5 , '89866'),
        'R_advcl'                       : (6 , '89866'),
        'L_advmod'                      : (7 , '529348'),
        'R_advmod'                      : (8 , '529348'),
        'L_agent'                       : (9 , '133534'),
        'R_agent'                       : (10 , '133534'),
        'L_amod'                        : (11 , '2582385'),
        'R_amod'                        : (12 , '2582385'),
        'L_appos'                       : (13 , '480484'),
        'R_appos'                       : (14 , '480484'),
        'L_arg'                         : (15 , '-1'),
        'R_arg'                         : (16 , '-1'),
        'L_attr'                        : (17 , '2655'),
        'R_attr'                        : (18 , '2655'),
        'L_aux'                         : (19 , '347737'),
        'R_aux'                         : (20 , '347737'),
        'L_auxpass'                     : (21 , '452443'),
        'R_auxpass'                     : (22 , '452443'),
        'L_cc'                          : (23 , '11394'),
        'R_cc'                          : (24 , '11394'),
        'L_ccomp'                       : (25 , '161394'),
        'R_ccomp'                       : (26 , '161394'),
        'L_comp'                        : (27 , '-1'),
        'R_comp'                        : (28 , '-1'),
        'L_complm'                      : (29 , '116411'),
        'R_complm'                      : (30 , '116411'),
        'L_conj'                        : (31 , '3610'),
        'R_conj'                        : (32 , '3610'),
        'L_conj_+'                      : (33 , '3474'),
        'R_conj_+'                      : (34 , '3474'),
        'L_conj_+/-'                    : (35 , '3544'),
        'R_conj_+/-'                    : (36 , '3544'),
        'L_conj_-'                      : (37 , '4619'),
        'R_conj_-'                      : (38 , '4619'),
        'L_conj_16s'                    : (39 , '23'),
        'R_conj_16s'                    : (40 , '23'),
        'L_conj_20e'                    : (41 , '62'),
        'R_conj_20e'                    : (42 , '62'),
        'L_conj_and'                    : (43 , '1109870'),
        'R_conj_and'                    : (44 , '1109870'),
        'L_conj_and/or'                 : (45 , '4233'),
        'R_conj_and/or'                 : (46 , '4233'),
        'L_conj_as'                     : (47 , '145'),
        'R_conj_as'                     : (48 , '145'),
        'L_conj_but'                    : (49 , '31863'),
        'R_conj_but'                    : (50 , '31863'),
        'L_conj_early'                  : (51 , '41'),
        'R_conj_early'                  : (52 , '41'),
        'L_conj_effectively'            : (53 , '16'),
        'R_conj_effectively'            : (54 , '16'),
        'L_conj_efficiently'            : (55 , '46'),
        'R_conj_efficiently'            : (56 , '46'),
        'L_conj_especially'             : (57 , '17'),
        'R_conj_especially'             : (58 , '17'),
        'L_conj_even'                   : (59 , '27'),
        'R_conj_even'                   : (60 , '27'),
        'L_conj_far'                    : (61 , '20'),
        'R_conj_far'                    : (62 , '20'),
        'L_conj_hence'                  : (63 , '15'),
        'R_conj_hence'                  : (64 , '15'),
        'L_conj_in'                     : (65 , '18'),
        'R_conj_in'                     : (66 , '18'),
        'L_conj_infections.'            : (67 , '18'),
        'R_conj_infections.'            : (68 , '18'),
        'L_conj_int.'                   : (69 , '61'),
        'R_conj_int.'                   : (70 , '61'),
        'L_conj_less'                   : (71 , '15'),
        'R_conj_less'                   : (72 , '15'),
        'L_conj_minus'                  : (73 , '90'),
        'R_conj_minus'                  : (74 , '90'),
        'L_conj_much'                   : (75 , '32'),
        'R_conj_much'                   : (76 , '32'),
        'L_conj_negcc'                  : (77 , '6917'),
        'R_conj_negcc'                  : (78 , '6917'),
        'L_conj_neither'                : (79 , '17'),
        'R_conj_neither'                : (80 , '17'),
        'L_conj_no'                     : (81 , '95'),
        'R_conj_no'                     : (82 , '95'),
        'L_conj_nor'                    : (83 , '1839'),
        'R_conj_nor'                    : (84 , '1839'),
        'L_conj_only'                   : (85 , '229'),
        'R_conj_only'                   : (86 , '229'),
        'L_conj_or'                     : (87 , '103403'),
        'R_conj_or'                     : (88 , '103403'),
        'L_conj_other'                  : (89 , '432'),
        'R_conj_other'                  : (90 , '432'),
        'L_conj_pao1'                   : (91 , '279'),
        'R_conj_pao1'                   : (92 , '279'),
        'L_conj_particularly'           : (93 , '20'),
        'R_conj_particularly'           : (94 , '20'),
        'L_conj_plus'                   : (95 , '2460'),
        'R_conj_plus'                   : (96 , '2460'),
        'L_conj_possibly'               : (97 , '30'),
        'R_conj_possibly'               : (98 , '30'),
        'L_conj_probably'               : (99 , '29'),
        'R_conj_probably'               : (100 , '29'),
        'L_conj_still'                  : (101 , '15'),
        'R_conj_still'                  : (102 , '15'),
        'L_conj_such'                   : (103 , '446'),
        'R_conj_such'                   : (104 , '446'),
        'L_conj_than'                   : (105 , '140'),
        'R_conj_than'                   : (106 , '140'),
        'L_conj_then'                   : (107 , '26'),
        'R_conj_then'                   : (108 , '26'),
        'L_conj_thus'                   : (109 , '40'),
        'R_conj_thus'                   : (110 , '40'),
        'L_conj_together'               : (111 , '388'),
        'R_conj_together'               : (112 , '388'),
        'L_conj_versus'                 : (113 , '2646'),
        'R_conj_versus'                 : (114 , '2646'),
        'L_conj_vs'                     : (115 , '1023'),
        'R_conj_vs'                     : (116 , '1023'),
        'L_conj_vs.'                    : (117 , '1684'),
        'R_conj_vs.'                    : (118 , '1684'),
        'L_conj_with'                   : (119 , '354'),
        'R_conj_with'                   : (120 , '354'),
        'L_conj_x'                      : (121 , '5298'),
        'R_conj_x'                      : (122 , '5298'),
        'L_conj_yet'                    : (123 , '594'),
        'R_conj_yet'                    : (124 , '594'),
        'L_cop'                         : (125 , '250300'),
        'R_cop'                         : (126 , '250300'),
        'L_csubj'                       : (127 , '2767'),
        'R_csubj'                       : (128 , '2767'),
        'L_csubjpass'                   : (129 , '655'),
        'R_csubjpass'                   : (130 , '655'),
        'L_dep'                         : (131 , '985391'),
        'R_dep'                         : (132 , '985391'),
        'L_det'                         : (133 , '1820715'),
        'R_det'                         : (134 , '1820715'),
        'L_dobj'                        : (135 , '825492'),
        'R_dobj'                        : (136 , '825492'),
        'L_expl'                        : (137 , '10514'),
        'R_expl'                        : (138 , '10514'),
        'L_goeswith'                    : (139 , '-1'),
        'R_goeswith'                    : (140 , '-1'),
        'L_hyphen'                      : (141 , '40102'),
        'R_hyphen'                      : (142 , '40102'),
        'L_infmod'                      : (143 , '26289'),
        'R_infmod'                      : (144 , '26289'),
        'L_iobj'                        : (145 , '2715'),
        'R_iobj'                        : (146 , '2715'),
        'L_mark'                        : (147 , '76227'),
        'R_mark'                        : (148 , '76227'),
        'L_mod'                         : (149 , '-1'),
        'R_mod'                         : (150 , '-1'),
        'L_mwe'                         : (151 , '8650'),
        'R_mwe'                         : (152 , '8650'),
        'L_neg'                         : (153 , '53531'),
        'R_neg'                         : (154 , '53531'),
        'L_nn'                          : (155 , '3686900'),
        'R_nn'                          : (156 , '3686900'),
        'L_npadvmod'                    : (157 , '9509'),
        'R_npadvmod'                    : (158 , '9509'),
        'L_nsubj'                       : (159 , '953057'),
        'R_nsubj'                       : (160 , '953057'),
        'L_nsubjpass'                   : (161 , '512561'),
        'R_nsubjpass'                   : (162 , '512561'),
        'L_num'                         : (163 , '706844'),
        'R_num'                         : (164 , '706844'),
        'L_number'                      : (165 , '61331'),
        'R_number'                      : (166 , '61331'),
        'L_obj'                         : (167 , '-1'),
        'R_obj'                         : (168 , '-1'),
        'L_parataxis'                   : (169 , '27479'),
        'R_parataxis'                   : (170 , '27479'),
        'L_partmod'                     : (171 , '329351'),
        'R_partmod'                     : (172 , '329351'),
        'L_pcomp'                       : (173 , '9570'),
        'R_pcomp'                       : (174 , '9570'),
        'L_pobj'                        : (175 , '54915'),
        'R_pobj'                        : (176 , '54915'),
        'L_poss'                        : (177 , '82736'),
        'R_poss'                        : (178 , '82736'),
        'L_possessive'                  : (179 , '5766'),
        'R_possessive'                  : (180 , '5766'),
        'L_preconj'                     : (181 , '28181'),
        'R_preconj'                     : (182 , '28181'),
        'L_predet'                      : (183 , '4327'),
        'R_predet'                      : (184 , '4327'),
        'L_prep'                        : (185 , '25857'),
        'R_prep'                        : (186 , '25857'),
        'L_prep_about'                  : (187 , '2789'),
        'R_prep_about'                  : (188 , '2789'),
        'L_prep_above'                  : (189 , '703'),
        'R_prep_above'                  : (190 , '703'),
        'L_prep_according_to'           : (191 , '187'),
        'R_prep_according_to'           : (192 , '187'),
        'L_prep_across'                 : (193 , '2187'),
        'R_prep_across'                 : (194 , '2187'),
        'L_prep_after'                  : (195 , '24414'),
        'R_prep_after'                  : (196 , '24414'),
        'L_prep_against'                : (197 , '49973'),
        'R_prep_against'                : (198 , '49973'),
        'L_prep_albeit'                 : (199 , '35'),
        'R_prep_albeit'                 : (200 , '35'),
        'L_prep_along'                  : (201 , '574'),
        'R_prep_along'                  : (202 , '574'),
        'L_prep_along_with'             : (203 , '174'),
        'R_prep_along_with'             : (204 , '174'),
        'L_prep_alongside'              : (205 , '53'),
        'R_prep_alongside'              : (206 , '53'),
        'L_prep_although'               : (207 , '151'),
        'R_prep_although'               : (208 , '151'),
        'L_prep_among'                  : (209 , '19677'),
        'R_prep_among'                  : (210 , '19677'),
        'L_prep_amongst'                : (211 , '580'),
        'R_prep_amongst'                : (212 , '580'),
        'L_prep_apart_from'             : (213 , '377'),
        'R_prep_apart_from'             : (214 , '377'),
        'L_prep_around'                 : (215 , '1270'),
        'R_prep_around'                 : (216 , '1270'),
        'L_prep_as'                     : (217 , '72538'),
        'R_prep_as'                     : (218 , '72538'),
        'L_prep_as_for'                 : (219 , '38'),
        'R_prep_as_for'                 : (220 , '38'),
        'L_prep_as_of'                  : (221 , '42'),
        'R_prep_as_of'                  : (222 , '42'),
        'L_prep_as_per'                 : (223 , '21'),
        'R_prep_as_per'                 : (224 , '21'),
        'L_prep_as_to'                  : (225 , '65'),
        'R_prep_as_to'                  : (226 , '65'),
        'L_prep_aside_from'             : (227 , '56'),
        'R_prep_aside_from'             : (228 , '56'),
        'L_prep_assuming'               : (229 , '30'),
        'R_prep_assuming'               : (230 , '30'),
        'L_prep_astride'                : (231 , '-1'),
        'R_prep_astride'                : (232 , '-1'),
        'L_prep_at'                     : (233 , '61235'),
        'R_prep_at'                     : (234 , '61235'),
        'L_prep_away_from'              : (235 , '137'),
        'R_prep_away_from'              : (236 , '137'),
        'L_prep_based_on'               : (237 , '338'),
        'R_prep_based_on'               : (238 , '338'),
        'L_prep_because'                : (239 , '129'),
        'R_prep_because'                : (240 , '129'),
        'L_prep_because_of'             : (241 , '1545'),
        'R_prep_because_of'             : (242 , '1545'),
        'L_prep_before'                 : (243 , '2659'),
        'R_prep_before'                 : (244 , '2659'),
        'L_prep_behind'                 : (245 , '62'),
        'R_prep_behind'                 : (246 , '62'),
        'L_prep_below'                  : (247 , '746'),
        'R_prep_below'                  : (248 , '746'),
        'L_prep_beneath'                : (249 , '30'),
        'R_prep_beneath'                : (250 , '30'),
        'L_prep_beside'                 : (251 , '-1'),
        'R_prep_beside'                 : (252 , '-1'),
        'L_prep_besides'                : (253 , '559'),
        'R_prep_besides'                : (254 , '559'),
        'L_prep_between'                : (255 , '51246'),
        'R_prep_between'                : (256 , '51246'),
        'L_prep_beyond'                 : (257 , '371'),
        'R_prep_beyond'                 : (258 , '371'),
        'L_prep_by'                     : (259 , '79229'),
        'R_prep_by'                     : (260 , '79229'),
        'L_prep_by_means_of'            : (261 , '1150'),
        'R_prep_by_means_of'            : (262 , '1150'),
        'L_prep_carrying'               : (263 , '16'),
        'R_prep_carrying'               : (264 , '16'),
        'L_prep_close_to'               : (265 , '408'),
        'R_prep_close_to'               : (266 , '408'),
        'L_prep_colonizing'             : (267 , '16'),
        'R_prep_colonizing'             : (268 , '16'),
        'L_prep_compared_to'            : (269 , '746'),
        'R_prep_compared_to'            : (270 , '746'),
        'L_prep_compared_with'          : (271 , '413'),
        'R_prep_compared_with'          : (272 , '413'),
        'L_prep_comprising'             : (273 , '190'),
        'R_prep_comprising'             : (274 , '190'),
        'L_prep_concerning'             : (275 , '245'),
        'R_prep_concerning'             : (276 , '245'),
        'L_prep_considering'            : (277 , '115'),
        'R_prep_considering'            : (278 , '115'),
        'L_prep_containing'             : (279 , '34'),
        'R_prep_containing'             : (280 , '34'),
        'L_prep_contrary_to'            : (281 , '229'),
        'R_prep_contrary_to'            : (282 , '229'),
        'L_prep_covering'               : (283 , '20'),
        'R_prep_covering'               : (284 , '20'),
        'L_prep_depending_on'           : (285 , '29'),
        'R_prep_depending_on'           : (286 , '29'),
        'L_prep_despite'                : (287 , '2776'),
        'R_prep_despite'                : (288 , '2776'),
        'L_prep_due'                    : (289 , '163'),
        'R_prep_due'                    : (290 , '163'),
        'L_prep_due_to'                 : (291 , '8127'),
        'R_prep_due_to'                 : (292 , '8127'),
        'L_prep_during'                 : (293 , '21483'),
        'R_prep_during'                 : (294 , '21483'),
        'L_prep_encoding'               : (295 , '43'),
        'R_prep_encoding'               : (296 , '43'),
        'L_prep_except'                 : (297 , '1291'),
        'R_prep_except'                 : (298 , '1291'),
        'L_prep_except_for'             : (299 , '472'),
        'R_prep_except_for'             : (300 , '472'),
        'L_prep_excluding'              : (301 , '44'),
        'R_prep_excluding'              : (302 , '44'),
        'L_prep_far_from'               : (303 , '47'),
        'R_prep_far_from'               : (304 , '47'),
        'L_prep_followed_by'            : (305 , '1539'),
        'R_prep_followed_by'            : (306 , '1539'),
        'L_prep_following'              : (307 , '5358'),
        'R_prep_following'              : (308 , '5358'),
        'L_prep_for'                    : (309 , '231915'),
        'R_prep_for'                    : (310 , '231915'),
        'L_prep_form'                   : (311 , '65'),
        'R_prep_form'                   : (312 , '65'),
        'L_prep_forming'                : (313 , '21'),
        'R_prep_forming'                : (314 , '21'),
        'L_prep_from'                   : (315 , '235680'),
        'R_prep_from'                   : (316 , '235680'),
        'L_prep_further'                : (317 , '23'),
        'R_prep_further'                : (318 , '23'),
        'L_prep_given'                  : (319 , '1105'),
        'R_prep_given'                  : (320 , '1105'),
        'L_prep_if'                     : (321 , '397'),
        'R_prep_if'                     : (322 , '397'),
        'L_prep_in'                     : (323 , '678857'),
        'R_prep_in'                     : (324 , '678857'),
        'L_prep_in_accordance_with'     : (325 , '375'),
        'R_prep_in_accordance_with'     : (326 , '375'),
        'L_prep_in_addition_to'         : (327 , '2444'),
        'R_prep_in_addition_to'         : (328 , '2444'),
        'L_prep_in_case_of'             : (329 , '267'),
        'R_prep_in_case_of'             : (330 , '267'),
        'L_prep_in_front_of'            : (331 , '94'),
        'R_prep_in_front_of'            : (332 , '94'),
        'L_prep_in_place_of'            : (333 , '150'),
        'R_prep_in_place_of'            : (334 , '150'),
        'L_prep_in_spite_of'            : (335 , '331'),
        'R_prep_in_spite_of'            : (336 , '331'),
        'L_prep_including'              : (337 , '29956'),
        'R_prep_including'              : (338 , '29956'),
        'L_prep_infecting'              : (339 , '18'),
        'R_prep_infecting'              : (340 , '18'),
        'L_prep_inhibiting'             : (341 , '17'),
        'R_prep_inhibiting'             : (342 , '17'),
        'L_prep_inside'                 : (343 , '462'),
        'R_prep_inside'                 : (344 , '462'),
        'L_prep_inside_of'              : (345 , '-1'),
        'R_prep_inside_of'              : (346 , '-1'),
        'L_prep_instead_of'             : (347 , '302'),
        'R_prep_instead_of'             : (348 , '302'),
        'L_prep_into'                   : (349 , '33988'),
        'R_prep_into'                   : (350 , '33988'),
        'L_prep_involving'              : (351 , '34'),
        'R_prep_involving'              : (352 , '34'),
        'L_prep_irrespective_of'        : (353 , '355'),
        'R_prep_irrespective_of'        : (354 , '355'),
        'L_prep_like'                   : (355 , '4952'),
        'R_prep_like'                   : (356 , '4952'),
        'L_prep_matching'               : (357 , '15'),
        'R_prep_matching'               : (358 , '15'),
        'L_prep_near'                   : (359 , '911'),
        'R_prep_near'                   : (360 , '911'),
        'L_prep_next_to'                : (361 , '152'),
        'R_prep_next_to'                : (362 , '152'),
        'L_prep_of'                     : (363 , '1262119'),
        'R_prep_of'                     : (364 , '1262119'),
        'L_prep_off'                    : (365 , '-1'),
        'R_prep_off'                    : (366 , '-1'),
        'L_prep_off_of'                 : (367 , '17'),
        'R_prep_off_of'                 : (368 , '17'),
        'L_prep_on'                     : (369 , '96305'),
        'R_prep_on'                     : (370 , '96305'),
        'L_prep_on_account_of'          : (371 , '25'),
        'R_prep_on_account_of'          : (372 , '25'),
        'L_prep_on_top_of'              : (373 , '27'),
        'R_prep_on_top_of'              : (374 , '27'),
        'L_prep_once'                   : (375 , '142'),
        'R_prep_once'                   : (376 , '142'),
        'L_prep_onto'                   : (377 , '1555'),
        'R_prep_onto'                   : (378 , '1555'),
        'L_prep_out'                    : (379 , '386'),
        'R_prep_out'                    : (380 , '386'),
        'L_prep_out_of'                 : (381 , '1259'),
        'R_prep_out_of'                 : (382 , '1259'),
        'L_prep_outside'                : (383 , '525'),
        'R_prep_outside'                : (384 , '525'),
        'L_prep_outside_of'             : (385 , '142'),
        'R_prep_outside_of'             : (386 , '142'),
        'L_prep_over'                   : (387 , '5584'),
        'R_prep_over'                   : (388 , '5584'),
        'L_prep_per'                    : (389 , '5883'),
        'R_prep_per'                    : (390 , '5883'),
        'L_prep_post'                   : (391 , '660'),
        'R_prep_post'                   : (392 , '660'),
        'L_prep_prior_to'               : (393 , '1825'),
        'R_prep_prior_to'               : (394 , '1825'),
        'L_prep_producing'              : (395 , '99'),
        'R_prep_producing'              : (396 , '99'),
        'L_prep_promoting'              : (397 , '15'),
        'R_prep_promoting'              : (398 , '15'),
        'L_prep_regarding'              : (399 , '710'),
        'R_prep_regarding'              : (400 , '710'),
        'L_prep_regardless_of'          : (401 , '652'),
        'R_prep_regardless_of'          : (402 , '652'),
        'L_prep_representing'           : (403 , '30'),
        'R_prep_representing'           : (404 , '30'),
        'L_prep_since'                  : (405 , '1258'),
        'R_prep_since'                  : (406 , '1258'),
        'L_prep_so'                     : (407 , '57'),
        'R_prep_so'                     : (408 , '57'),
        'L_prep_subsequent_to'          : (409 , '110'),
        'R_prep_subsequent_to'          : (410 , '110'),
        'L_prep_such'                   : (411 , '129'),
        'R_prep_such'                   : (412 , '129'),
        'L_prep_such_as'                : (413 , '28847'),
        'R_prep_such_as'                : (414 , '28847'),
        'L_prep_than'                   : (415 , '19008'),
        'R_prep_than'                   : (416 , '19008'),
        'L_prep_thanks_to'              : (417 , '26'),
        'R_prep_thanks_to'              : (418 , '26'),
        'L_prep_that'                   : (419 , '1802'),
        'R_prep_that'                   : (420 , '1802'),
        'L_prep_though'                 : (421 , '60'),
        'R_prep_though'                 : (422 , '60'),
        'L_prep_through'                : (423 , '9166'),
        'R_prep_through'                : (424 , '9166'),
        'L_prep_throughout'             : (425 , '1554'),
        'R_prep_throughout'             : (426 , '1554'),
        'L_prep_to'                     : (427 , '245107'),
        'R_prep_to'                     : (428 , '245107'),
        'L_prep_together_with'          : (429 , '2054'),
        'R_prep_together_with'          : (430 , '2054'),
        'L_prep_toward'                 : (431 , '1616'),
        'R_prep_toward'                 : (432 , '1616'),
        'L_prep_towards'                : (433 , '2126'),
        'R_prep_towards'                : (434 , '2126'),
        'L_prep_under'                  : (435 , '12276'),
        'R_prep_under'                  : (436 , '12276'),
        'L_prep_underneath'             : (437 , '23'),
        'R_prep_underneath'             : (438 , '23'),
        'L_prep_unlike'                 : (439 , '1604'),
        'R_prep_unlike'                 : (440 , '1604'),
        'L_prep_until'                  : (441 , '820'),
        'R_prep_until'                  : (442 , '820'),
        'L_prep_up'                     : (443 , '396'),
        'R_prep_up'                     : (444 , '396'),
        'L_prep_upon'                   : (445 , '5000'),
        'R_prep_upon'                   : (446 , '5000'),
        'L_prep_using'                  : (447 , '79'),
        'R_prep_using'                  : (448 , '79'),
        'L_prep_via'                    : (449 , '6223'),
        'R_prep_via'                    : (450 , '6223'),
        'L_prep_viz.'                   : (451 , '60'),
        'R_prep_viz.'                   : (452 , '60'),
        'L_prep_when'                   : (453 , '106'),
        'R_prep_when'                   : (454 , '106'),
        'L_prep_whereas'                : (455 , '195'),
        'R_prep_whereas'                : (456 , '195'),
        'L_prep_whether'                : (457 , '97'),
        'R_prep_whether'                : (458 , '97'),
        'L_prep_while'                  : (459 , '431'),
        'R_prep_while'                  : (460 , '431'),
        'L_prep_whilst'                 : (461 , '24'),
        'R_prep_whilst'                 : (462 , '24'),
        'L_prep_why'                    : (463 , '15'),
        'R_prep_why'                    : (464 , '15'),
        'L_prep_with'                   : (465 , '284177'),
        'R_prep_with'                   : (466 , '284177'),
        'L_prep_with_regard_to'         : (467 , '661'),
        'R_prep_with_regard_to'         : (468 , '661'),
        'L_prep_with_respect_to'        : (469 , '1961'),
        'R_prep_with_respect_to'        : (470 , '1961'),
        'L_prep_within'                 : (471 , '14902'),
        'R_prep_within'                 : (472 , '14902'),
        'L_prep_without'                : (473 , '5137'),
        'R_prep_without'                : (474 , '5137'),
        'L_prepc'                       : (475 , '-1'),
        'R_prepc'                       : (476 , '-1'),
        'L_prepc_about'                 : (477 , '131'),
        'R_prepc_about'                 : (478 , '131'),
        'L_prepc_according_to'          : (479 , '2184'),
        'R_prepc_according_to'          : (480 , '2184'),
        'L_prepc_across_from'           : (481 , '27'),
        'R_prepc_across_from'           : (482 , '27'),
        'L_prepc_after'                 : (483 , '1331'),
        'R_prepc_after'                 : (484 , '1331'),
        'L_prepc_against'               : (485 , '45'),
        'R_prepc_against'               : (486 , '45'),
        'L_prepc_along_with'            : (487 , '904'),
        'R_prepc_along_with'            : (488 , '904'),
        'L_prepc_although'              : (489 , '18'),
        'R_prepc_although'              : (490 , '18'),
        'L_prepc_among'                 : (491 , '18'),
        'R_prepc_among'                 : (492 , '18'),
        'L_prepc_apart_from'            : (493 , '24'),
        'R_prepc_apart_from'            : (494 , '24'),
        'L_prepc_around'                : (495 , '-1'),
        'R_prepc_around'                : (496 , '-1'),
        'L_prepc_as'                    : (497 , '1416'),
        'R_prepc_as'                    : (498 , '1416'),
        'L_prepc_as_for'                : (499 , '265'),
        'R_prepc_as_for'                : (500 , '265'),
        'L_prepc_as_of'                 : (501 , '43'),
        'R_prepc_as_of'                 : (502 , '43'),
        'L_prepc_as_per'                : (503 , '32'),
        'R_prepc_as_per'                : (504 , '32'),
        'L_prepc_as_to'                 : (505 , '245'),
        'R_prepc_as_to'                 : (506 , '245'),
        'L_prepc_at'                    : (507 , '634'),
        'R_prepc_at'                    : (508 , '634'),
        'L_prepc_based_on'              : (509 , '3662'),
        'R_prepc_based_on'              : (510 , '3662'),
        'L_prepc_because'               : (511 , '110'),
        'R_prepc_because'               : (512 , '110'),
        'L_prepc_because_of'            : (513 , '718'),
        'R_prepc_because_of'            : (514 , '718'),
        'L_prepc_before'                : (515 , '382'),
        'R_prepc_before'                : (516 , '382'),
        'L_prepc_besides'               : (517 , '53'),
        'R_prepc_besides'               : (518 , '53'),
        'L_prepc_between'               : (519 , '39'),
        'R_prepc_between'               : (520 , '39'),
        'L_prepc_by'                    : (521 , '9609'),
        'R_prepc_by'                    : (522 , '9609'),
        'L_prepc_compared_to'           : (523 , '3607'),
        'R_prepc_compared_to'           : (524 , '3607'),
        'L_prepc_compared_with'         : (525 , '2795'),
        'R_prepc_compared_with'         : (526 , '2795'),
        'L_prepc_considering'           : (527 , '19'),
        'R_prepc_considering'           : (528 , '19'),
        'L_prepc_contrary_to'           : (529 , '20'),
        'R_prepc_contrary_to'           : (530 , '20'),
        'L_prepc_depending_on'          : (531 , '625'),
        'R_prepc_depending_on'          : (532 , '625'),
        'L_prepc_despite'               : (533 , '273'),
        'R_prepc_despite'               : (534 , '273'),
        'L_prepc_due_to'                : (535 , '70'),
        'R_prepc_due_to'                : (536 , '70'),
        'L_prepc_during'                : (537 , '51'),
        'R_prepc_during'                : (538 , '51'),
        'L_prepc_except'                : (539 , '118'),
        'R_prepc_except'                : (540 , '118'),
        'L_prepc_except_for'            : (541 , '831'),
        'R_prepc_except_for'            : (542 , '831'),
        'L_prepc_far_from'              : (543 , '23'),
        'R_prepc_far_from'              : (544 , '23'),
        'L_prepc_followed_by'           : (545 , '31'),
        'R_prepc_followed_by'           : (546 , '31'),
        'L_prepc_for'                   : (547 , '8134'),
        'R_prepc_for'                   : (548 , '8134'),
        'L_prepc_from'                  : (549 , '657'),
        'R_prepc_from'                  : (550 , '657'),
        'L_prepc_given'                 : (551 , '15'),
        'R_prepc_given'                 : (552 , '15'),
        'L_prepc_if'                    : (553 , '49'),
        'R_prepc_if'                    : (554 , '49'),
        'L_prepc_in'                    : (555 , '8008'),
        'R_prepc_in'                    : (556 , '8008'),
        'L_prepc_in_addition_to'        : (557 , '252'),
        'R_prepc_in_addition_to'        : (558 , '252'),
        'L_prepc_in_spite_of'           : (559 , '16'),
        'R_prepc_in_spite_of'           : (560 , '16'),
        'L_prepc_instead_of'            : (561 , '31'),
        'R_prepc_instead_of'            : (562 , '31'),
        'L_prepc_into'                  : (563 , '138'),
        'R_prepc_into'                  : (564 , '138'),
        'L_prepc_irrespective_of'       : (565 , '53'),
        'R_prepc_irrespective_of'       : (566 , '53'),
        'L_prepc_of'                    : (567 , '7032'),
        'R_prepc_of'                    : (568 , '7032'),
        'L_prepc_on'                    : (569 , '591'),
        'R_prepc_on'                    : (570 , '591'),
        'L_prepc_out_of'                : (571 , '56'),
        'R_prepc_out_of'                : (572 , '56'),
        'L_prepc_outside_of'            : (573 , '54'),
        'R_prepc_outside_of'            : (574 , '54'),
        'L_prepc_over'                  : (575 , '42'),
        'R_prepc_over'                  : (576 , '42'),
        'L_prepc_owing_to'              : (577 , '27'),
        'R_prepc_owing_to'              : (578 , '27'),
        'L_prepc_prior_to'              : (579 , '78'),
        'R_prepc_prior_to'              : (580 , '78'),
        'L_prepc_regardless_of'         : (581 , '85'),
        'R_prepc_regardless_of'         : (582 , '85'),
        'L_prepc_since'                 : (583 , '22'),
        'R_prepc_since'                 : (584 , '22'),
        'L_prepc_such_as'               : (585 , '170'),
        'R_prepc_such_as'               : (586 , '170'),
        'L_prepc_than'                  : (587 , '327'),
        'R_prepc_than'                  : (588 , '327'),
        'L_prepc_that'                  : (589 , '639'),
        'R_prepc_that'                  : (590 , '639'),
        'L_prepc_through'               : (591 , '130'),
        'R_prepc_through'               : (592 , '130'),
        'L_prepc_to'                    : (593 , '814'),
        'R_prepc_to'                    : (594 , '814'),
        'L_prepc_toward'                : (595 , '70'),
        'R_prepc_toward'                : (596 , '70'),
        'L_prepc_towards'               : (597 , '83'),
        'R_prepc_towards'               : (598 , '83'),
        'L_prepc_under'                 : (599 , '28'),
        'R_prepc_under'                 : (600 , '28'),
        'L_prepc_until'                 : (601 , '39'),
        'R_prepc_until'                 : (602 , '39'),
        'L_prepc_upon'                  : (603 , '138'),
        'R_prepc_upon'                  : (604 , '138'),
        'L_prepc_via'                   : (605 , '48'),
        'R_prepc_via'                   : (606 , '48'),
        'L_prepc_whereas'               : (607 , '26'),
        'R_prepc_whereas'               : (608 , '26'),
        'L_prepc_whether'               : (609 , '82'),
        'R_prepc_whether'               : (610 , '82'),
        'L_prepc_while'                 : (611 , '200'),
        'R_prepc_while'                 : (612 , '200'),
        'L_prepc_with'                  : (613 , '2639'),
        'R_prepc_with'                  : (614 , '2639'),
        'L_prepc_without'               : (615 , '829'),
        'R_prepc_without'               : (616 , '829'),
        'L_prt'                         : (617 , '4860'),
        'R_prt'                         : (618 , '4860'),
        'L_punct'                       : (619 , '3654270'),
        'R_punct'                       : (620 , '3654270'),
        'L_purpcl'                      : (621 , '14060'),
        'R_purpcl'                      : (622 , '14060'),
        'L_quantmod'                    : (623 , '35423'),
        'R_quantmod'                    : (624 , '35423'),
        'L_rcmod'                       : (625 , '139942'),
        'R_rcmod'                       : (626 , '139942'),
        'L_ref'                         : (627 , '-1'),
        'R_ref'                         : (628 , '-1'),
        'L_rel'                         : (629 , '13133'),
        'R_rel'                         : (630 , '13133'),
        'L_root'                        : (631 , '-1'),
        'R_root'                        : (632 , '-1'),
        'L_sdep'                        : (633 , '-1'),
        'R_sdep'                        : (634 , '-1'),
        'L_slash'                       : (635 , '8689'),
        'R_slash'                       : (636 , '8689'),
        'L_subj'                        : (637 , '-1'),
        'R_subj'                        : (638 , '-1'),
        'L_tmod'                        : (639 , '1236'),
        'R_tmod'                        : (640 , '1236'),
        'L_vmod'                        : (641 , '-1'),
        'R_vmod'                        : (642 , '-1'),
        'L_xcomp'                       : (643 , '159222'),
        'R_xcomp'                       : (644 , '159222'),
        'L_xsubj'                       : (645 , '77005'),
        'R_xsubj'                       : (646 , '77005'),

        'R_acl'                         : (647 , 'UD SPECIFIC'),
        'L_acl'                         : (648 , 'UD SPECIFIC'),
        'R_case'                        : (649 , 'UD SPECIFIC'),
        'L_case'                        : (650 , 'UD SPECIFIC'),
        'R_clf'                         : (651 , 'UD SPECIFIC'),
        'L_clf'                         : (652 , 'UD SPECIFIC'),
        'R_compound'                    : (653 , 'UD SPECIFIC'),
        'L_compound'                    : (654 , 'UD SPECIFIC'),
        'R_discourse'                   : (655 , 'UD SPECIFIC'),
        'L_discourse'                   : (656 , 'UD SPECIFIC'),
        'R_dislocated'                  : (657 , 'UD SPECIFIC'),
        'L_dislocated'                  : (658 , 'UD SPECIFIC'),
        'R_fixed'                       : (659 , 'UD SPECIFIC'),
        'L_fixed'                       : (660 , 'UD SPECIFIC'),
        'R_flat'                        : (661 , 'UD SPECIFIC'),
        'L_flat'                        : (662 , 'UD SPECIFIC'),
        'R_list'                        : (663 , 'UD SPECIFIC'),
        'L_list'                        : (664 , 'UD SPECIFIC'),
        'R_nmod'                        : (665 , 'UD SPECIFIC'),
        'L_nmod'                        : (666 , 'UD SPECIFIC'),
        'R_nummod'                      : (667 , 'UD SPECIFIC'),
        'L_nummod'                      : (668 , 'UD SPECIFIC'),
        'R_obl'                         : (669 , 'UD SPECIFIC'),
        'L_obl'                         : (670 , 'UD SPECIFIC'),
        'R_orphan'                      : (671 , 'UD SPECIFIC'),
        'L_orphan'                      : (672 , 'UD SPECIFIC'),
        'R_reparandum'                  : (673 , 'UD SPECIFIC'),
        'L_reparandum'                  : (674 , 'UD SPECIFIC'),
        'R_vocative'                    : (675 , 'UD SPECIFIC'),
        'L_vocative'                    : (676 , 'UD SPECIFIC'),
        'R_name'                        : (677 , 'OLD UD SPECIFIC'),
        'L_name'                        : (678 , 'OLD UD SPECIFIC'),
        'R_acl:relcl'                   : (679 , 'UD ENG SPECIFIC'),
        'L_acl:relcl'                   : (680 , 'UD ENG SPECIFIC'),
        'R_nmod:npmod'                  : (681 , 'UD ENG SPECIFIC'),
        'L_nmod:npmod'                  : (682 , 'UD ENG SPECIFIC'),
        'R_nmod:poss'                   : (683 , 'UD ENG SPECIFIC'),
        'L_nmod:poss'                   : (684 , 'UD ENG SPECIFIC'),
        'R_nmod:tmod'                   : (685 , 'UD ENG SPECIFIC'),
        'L_nmod:tmod'                   : (686 , 'UD ENG SPECIFIC'),
        'ADDED_OTHER'                   : (687 , ''),
}

def Give_POSTAG_OneHotEncodingAsEmbedding ():
    length = len(PENN_TB_POS_TAGS); 
    a = np.zeros ((length+1,length) , dtype=np.float32); 
    for i in range(length):
        a[i+1,i]=1 ; 
    return a ; 

def Give_STANFORD_DEPTP_OneHotEncodingAsEmbedding ():
    length = len(STANFORD_DEPTP_TAGS); 
    a = np.zeros ((length+1,length) , dtype=np.float32); 
    for i in range(length):
        a[i+1,i]=1 ; 
    return a ; 
